"""Pipeline Executor - Runs execution plans generated by COE.

This module executes ExecutionPlan objects by dispatching steps to appropriate
runners (python scripts, passthrough, agent calls) and managing artifact flow.
"""

from __future__ import annotations

from collections.abc import Callable
import importlib.util
import os
from pathlib import Path
import sys
from typing import Any

from dta.dti.coe.llm import get_llm_router
from dta.dti.registry import get_item, load_registry
from dta.dti.schemas import ExecutionPlan, PlanStep, Registry, RegistryItem


class ExecutionError(Exception):
    """Raised when step execution fails."""


class MissingInputError(ExecutionError):
    """Raised when required input is missing.

    This is a recoverable error - the system can prompt the user
    to provide the missing input rather than failing completely.
    """

    def __init__(self, step_id: str, input_type: str, message: str | None = None) -> None:
        self.step_id = step_id
        self.input_type = input_type
        default_msg = f"Missing required input '{input_type}' for step '{step_id}'"
        super().__init__(message or default_msg)


class CancellationError(Exception):
    """Raised when execution is cancelled."""


class PipelineExecutor:
    """Executes pipeline plans by dispatching steps to registered runners.

    The executor maintains an artifact dictionary that gets populated as steps
    execute. Each step can read from and write to this shared state.

    Example:
        >>> executor = PipelineExecutor()
        >>> plan = ExecutionPlan(steps=[...])
        >>> result = executor.execute(plan)
        >>> print(result["artifacts"])
    """

    def __init__(self, registry: Registry | None = None) -> None:
        """Initialize executor with optional registry.

        Args:
            registry: Component registry. If None, loads from default path.
        """
        self.registry = registry or load_registry()
        self.artifacts: dict[str, Any] = {}

    def execute(
        self,
        plan: ExecutionPlan,
        on_progress: Callable[[dict[str, Any]], None] | None = None,
        is_cancelled: Callable[[], bool] | None = None,
    ) -> dict[str, Any]:
        """Execute a pipeline plan step by step.

        Args:
            plan: Execution plan from COE planner
            on_progress: Optional callback for progress events
            is_cancelled: Optional callback to check if execution should be cancelled

        Returns:
            Dictionary with:
                - flow: Flow name
                - steps: List of executed step IDs
                - artifacts: All generated artifacts
                - outputs: Final output artifacts

        Raises:
            ExecutionError: If any step fails
            CancellationError: If execution is cancelled
        """
        self.artifacts = {}  # Reset for each execution
        executed_steps: list[str] = []

        for idx, step in enumerate(plan.steps, start=1):
            # Check for cancellation before each step
            if is_cancelled and is_cancelled():
                raise CancellationError("Execution cancelled by user")

            if on_progress:
                on_progress(
                    {
                        "event": "step_start",
                        "index": idx,
                        "total": len(plan.steps),
                        "step_id": step.uses,
                    }
                )

            try:
                item = get_item(self.registry, step.uses)
                self._execute_step(step, item)
                executed_steps.append(step.uses)

                if on_progress:
                    on_progress(
                        {
                            "event": "step_complete",
                            "index": idx,
                            "total": len(plan.steps),
                            "step_id": step.uses,
                        }
                    )

            except Exception as e:
                if on_progress:
                    on_progress(
                        {
                            "event": "step_error",
                            "index": idx,
                            "step_id": step.uses,
                            "error": str(e),
                        }
                    )
                raise ExecutionError(f"Step {step.uses} failed: {e}") from e

        # Collect final outputs
        final_outputs = {}
        for output_key in plan.outputs:
            if ":" in output_key:  # e.g., "publish: chat"
                _, key = output_key.split(":", 1)
                key = key.strip()
                if key in self.artifacts:
                    final_outputs[key] = self.artifacts[key]
            elif output_key in self.artifacts:
                final_outputs[output_key] = self.artifacts[output_key]

        return {
            "flow": plan.flow,
            "steps": executed_steps,
            "artifacts": self.artifacts,
            "outputs": final_outputs,
        }

    def _execute_step(self, step: PlanStep, item: RegistryItem) -> None:
        """Execute a single pipeline step.

        Args:
            step: Step configuration
            item: Registry item with runner config

        Raises:
            ExecutionError: If runner type is unknown or execution fails
        """
        runner_type = item.runner.type

        if runner_type == "passthrough":
            self._run_passthrough(step, item)
        elif runner_type == "python":
            self._run_python(step, item)
        elif runner_type == "agent":
            self._run_agent(step, item)
        else:
            raise ExecutionError(f"Unknown runner type: {runner_type}")

    def _run_passthrough(self, step: PlanStep, item: RegistryItem) -> None:
        """Handle passthrough runners (e.g., input/file).

        Passthrough simply forwards input values to outputs without processing.
        Useful for file inputs where the path is provided by the user.

        Args:
            step: Step configuration (may contain binds with values)
            item: Registry item

        Raises:
            ExecutionError: If required output has no binding
        """
        # For passthrough, binds in step contain the actual values
        # Example: step.binds = {"RasterPath": "/path/to/file.tif"}
        for output_type in item.outputs:
            if output_type in step.binds:
                self.artifacts[output_type] = step.binds[output_type]
            else:
                # Input steps require file bindings to work
                if step.uses.startswith("input/"):
                    raise MissingInputError(
                        step_id=step.uses,
                        input_type=output_type,
                        message=_get_friendly_missing_input_message(step.uses, output_type),
                    )
                # For other passthrough steps, mark as pending
                self.artifacts[output_type] = None

    def _run_python(self, step: PlanStep, item: RegistryItem) -> None:
        """Execute Python entrypoint.

        Loads the Python module specified in item.runner.entrypoint and calls
        its main function or runs it as a script.

        Args:
            step: Step configuration
            item: Registry item with entrypoint path

        Raises:
            ExecutionError: If entrypoint not found or execution fails
        """
        if not item.runner.entrypoint:
            raise ExecutionError(f"Python runner {item.id} missing entrypoint")

        entrypoint = Path(item.runner.entrypoint)
        if not entrypoint.is_absolute():
            # Relative to project root
            from dta.config import ROOT_DIR

            entrypoint = ROOT_DIR / entrypoint

        if not entrypoint.exists():
            raise ExecutionError(f"Entrypoint not found: {entrypoint}")

        # Set environment variables from runner config
        old_env = {}
        for key, value in item.runner.env.items():
            old_env[key] = os.environ.get(key)
            # Resolve relative paths in env vars
            if key.endswith(("_DIR", "_PATH")) and not Path(value).is_absolute():
                from dta.config import ROOT_DIR

                value = str(ROOT_DIR / value)
            os.environ[key] = value

        try:
            # Collect inputs from artifacts
            inputs: dict[str, Any] = {}
            for input_type in item.inputs:
                if input_type in self.artifacts:
                    inputs[input_type] = self.artifacts[input_type]

            # Load and execute module
            spec = importlib.util.spec_from_file_location(f"runner_{item.id.replace('/', '_')}", str(entrypoint))
            if spec is None or spec.loader is None:
                raise ExecutionError(f"Failed to load module: {entrypoint}")

            module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = module
            spec.loader.exec_module(module)

            # Look for run() or main() function
            if hasattr(module, "run"):
                result = module.run(**inputs)
            elif hasattr(module, "main"):
                result = module.main(**inputs)
            else:
                raise ExecutionError(f"Module {entrypoint} has no run() or main()")

            # Store outputs
            if len(item.outputs) == 1:
                self.artifacts[item.outputs[0]] = result
            elif isinstance(result, dict):
                for output_type in item.outputs:
                    if output_type in result:
                        self.artifacts[output_type] = result[output_type]
            else:
                raise ExecutionError(f"Cannot map result to outputs {item.outputs}. Expected dict or single output.")

        finally:
            # Restore environment
            for key, value in old_env.items():
                if value is None:
                    os.environ.pop(key, None)
                else:
                    os.environ[key] = value

    def _run_agent(self, step: PlanStep, item: RegistryItem) -> None:
        """Execute agent runner (LLM-based processing).

        Agent runners invoke LLM for summarization, analysis, or other
        natural language processing tasks.

        Args:
            step: Step configuration
            item: Registry item

        Raises:
            ExecutionError: If agent execution fails
        """
        # Collect inputs
        # If agent has no specific inputs, pass all available artifacts
        if not item.inputs:
            inputs = dict(self.artifacts)  # Pass all artifacts to agent
        else:
            inputs: dict[str, Any] = {}
            for input_type in item.inputs:
                if input_type in self.artifacts:
                    inputs[input_type] = self.artifacts[input_type]

        # For now, implement basic summarization
        # TODO: Expand with different agent types based on item.id
        if item.id == "post-processing/agent-analysis":
            result = self._agent_summarize(inputs)
            # Store in outputs
            if item.outputs:
                self.artifacts[item.outputs[0]] = result
            else:
                # Store as generic output
                self.artifacts["agent_result"] = result
        else:
            raise ExecutionError(f"Unknown agent type: {item.id}")

    def _agent_summarize(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Use LLM to summarize analysis results.

        Uses LLM router with automatic Gemini → Ollama fallback.

        Args:
            inputs: Dictionary of input artifacts

        Returns:
            Dictionary with summary text
        """
        try:
            router = get_llm_router()

            # Determine analysis type from artifact keys
            analysis_type = self._detect_analysis_type(inputs)

            # Format inputs for LLM
            context = []
            for key, value in inputs.items():
                # Skip large arrays (like ndvi_array) - just note they exist
                if key.endswith("_array") or key == "ndvi_array":
                    context.append(f"{key}: [array data available]")
                    continue
                # Truncate large values for context
                value_str = str(value)
                if len(value_str) > 500:
                    value_str = value_str[:500] + "... (truncated)"
                context.append(f"{key}: {value_str}")

            prompt = (
                f"You just completed a {analysis_type} analysis. "
                "Summarize the results in 2-3 sentences. Be concise and focus on key insights. "
                "Do NOT ask questions - just summarize what the data shows:\n\n" + "\n".join(context)
            )

            # Use router with automatic fallback
            from dta.dti.coe.llm import LLMMessage

            response = router.generate(
                messages=[
                    LLMMessage(role="user", content=prompt),
                ],
                temperature=0.7,
            )

            return {
                "summary": response.text,
                "inputs": inputs,
                "llm_provider": response.provider,  # Track which provider was used
            }

        except Exception as e:
            # Graceful degradation if all LLMs fail
            return {
                "summary": f"Analysis complete. Results available but summarization failed: {e}",
                "inputs": inputs,
            }

    def _detect_analysis_type(self, inputs: dict[str, Any]) -> str:
        """Detect the type of analysis from artifact keys.

        Args:
            inputs: Dictionary of input artifacts

        Returns:
            Human-readable analysis type description
        """
        keys = set(inputs.keys())

        # Check for specific analysis markers
        if "ndvi_array" in keys or "NDVIMap" in keys:
            return "NDVI (Normalized Difference Vegetation Index)"
        if "change_array" in keys or "ChangeMap" in keys:
            return "change detection"
        if "FieldBoundaries" in keys or "boundaries" in keys:
            return "field boundary detection"
        if "Features" in keys or "embeddings" in keys:
            return "Prithvi feature extraction"
        if "Statistics" in keys or "statistics" in keys:
            return "raster statistics"

        # Generic fallback
        return "geospatial"


def _get_friendly_missing_input_message(step_id: str, input_type: str) -> str:
    """Generate a user-friendly message for missing input.

    Args:
        step_id: The step that needs the input (e.g., "input/file")
        input_type: The type of input needed (e.g., "RasterPath")

    Returns:
        User-friendly error message with guidance
    """
    messages = {
        "input/file": ("I need a file to process this request. Please upload a GeoTIFF image and try again."),
        "input/file-before": (
            "I need a 'before' image for change detection. Please upload the earlier date GeoTIFF image."
        ),
        "input/file-after": (
            "I need an 'after' image for change detection. Please upload the later date GeoTIFF image."
        ),
    }

    if step_id in messages:
        return messages[step_id]

    # Fallback based on input type
    if "Raster" in input_type or "Path" in input_type:
        return (
            f"I need a file to continue. Please upload a GeoTIFF image for the {step_id.replace('input/', '')} input."
        )

    return f"Missing required input for {step_id}. Please provide the necessary data and try again."
